Launch Linux browser windows in different sessions
blimmer/zsh-aws-vault pull request #11
Opened 2020-01-18 16:19 UTC by hlascelles

If `google-chrome` is present, launch a new session window for each invocation.

2020-01-23 19:26 UTC, blimmer requested changes
Hi @hlascelles, and thank you for taking the time to create this PR. Since this is the first logic explicitly intended for Linux, I added an inline comment asking if you could create the skeleton for other Linux logic in the future.

If you have the time to make those changes, that would be great! If not, let me know, and I can try to find some time to add that and integrate your logic. Thanks!

2020-01-23 19:26 UTC, blimmer commented on zsh-aws-vault.plugin.zsh
> +  elif (command -v "google-chrome" > /dev/null); then
I'd love to see this block follow the pattern above, e.g.

```
elif _using_linux ; then
  case $browser in
     google-chrome)
         #your logic
         ;;
   esac
```

That should be pretty straightforward to do, by adding a `uname` check for `Linux` and adjusting the `_find_browser` to have logic for Linux (using the `command -v` logic you have would be perfect). It's totally fine if you only implement the `google-chrome` logic and leave the rest for others who are willing to PR the project for Firefox, etc.

2020-01-31 13:24 UTC, hlascelles commented
Sure thing, I will look into it :+1:

2020-03-17 09:10 UTC, hlascelles commented
So, turns out that much of the Mac line also worked. On Linux it makes sense to maximise it too though.

How does it look?

2020-03-19 21:55 UTC, blimmer approved these changes
This looks great! Thank you for making the requested changed :-)

2020-03-19 21:56 UTC, merged